name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}  # Replace with your actual Docker Hub username
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_IMAGE_NAME }}     # Replace with your desired image name
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}  # Add your Heroku API key here
      HEROKU_APP_NAME: coreuser  # Replace with your Heroku app name

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package -DskipTests

      #- name: Run Tests
      #  run: mvn test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Make sure to store this in GitHub Secrets
          password: ${{ secrets.DOCKER_HUB_TOKEN }}       # Make sure to store this in GitHub Secrets

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest

      # New steps for Heroku deployment
      - name: Log in to Heroku Container Registry
        run: |
          echo "Logging into Heroku..."
          echo ${{ secrets.HEROKU_API_KEY }} | docker login --username=_ --password-stdin registry.heroku.com

      - name: Push Docker image to Heroku
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:latest registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release the application on Heroku
        run: heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}
