name: CI-CD Pipeline

on:
  push:
    branches: [ main ]
 # pull_request:
 #   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: madanamgoth  # Replace with your actual Docker Hub username
      DOCKER_IMAGE_NAME: coreuser          # Replace with your desired image name

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run Tests
      run: mvn test

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  # Make sure to store this in GitHub Secrets
        password: ${{ secrets.DOCKER_HUB_TOKEN }}       # Make sure to store this in GitHub Secrets

    - name: Build Docker image
      run: docker build -t madanamgoth/coreuser:latest .

    - name: Push Docker image to Docker Hub
      run: docker push madanamgoth/coreuser:latest
